const DEFAULT_TOKEN_CONTRACT_ADDRESS = "0x0000000000000000000000000000000000000000";
const DEFAULT_TOKEN_ID = 0;
const DEFAULT_MAX_DEMAND_VOLUME = 100;
const DEFAULT_EPOCH_CAPACITY = 50;
const DEFAULT_EPOCH_DURATION = 2000;
const DEFAULT_ETHER_MULTIPLIER = 10;
const DEFAULT_EXPIRATION_BLOCKS = 10000;
const DEFAULT_ENABLE_WITHDRAW = true;
const DEFAULT_DEPLOYMENT_VALUE = 250;

module.exports = {
    DEFAULT_TOKEN_CONTRACT_ADDRESS,
    DEFAULT_TOKEN_ID,
    DEFAULT_MAX_DEMAND_VOLUME,
    DEFAULT_EPOCH_CAPACITY,
    DEFAULT_EPOCH_DURATION,
    DEFAULT_ETHER_MULTIPLIER,
    DEFAULT_EXPIRATION_BLOCKS,
    DEFAULT_ENABLE_WITHDRAW,
    DEFAULT_DEPLOYMENT_VALUE,
};